In [64]:
### NumPy(Numerical Python) 활용
import numpy as np


# 1. shape을 조절해서 내가 원하는 형태의 ndarray를 만들어보자.
# 중간에 내가 원하는 형태로 바꿀 수 있다.

arr = np.arange(0,12,1)
print(arr)
# 결과 : [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 2차원으로 변경하자(4행 3열로 바꿔보자)
# reshape을 이용하면 view가 만들어진다. => view이기 때문에 실제 원본 데이터는 (arr) 1 개이다.
# 따라서 arr을 변경하면  arr1의 데이터도 변경된다. !!!! 오오오!! 
arr1 = arr.reshape(4,3)
print(arr1)
# 결과 : 
#[[ 0  1  2]
# [ 3  4  5]
# [ 6  7  8]
# [ 9 10 11]]

arr[1] = 100
print(arr)
# 결과 : [  0 100   2   3   4   5   6   7   8   9  10  11]
print(arr1)
# 결과 : 
#[[  0 100   2]
# [  3   4   5]
# [  6   7   8]
# [  9  10  11]]

# view는 base 속성을 갖고 있다.
# base : view만 가진 속성, 어떤 데이터가 원본인지 보여준다
print((arr1.base) is arr)
# 결과 ;  True


# shpae을 변경해서 새로운 ndarray를 만들어보자 => copy 이용
arr = np.arange(0,12,1)
arr1 = arr.reshape(4,3).copy()    #새로운 ndarray를 생성

arr1 = arr.reshape(5,3) # 형태가 맞지 않기 때문에 ERROR가 난다.

arr1 = arr.reshape(4,3)
print(arr1)
# 결과 : 
#[[ 0  1  2]
# [ 3  4  5]
# [ 6  7  8]
# [ 9 10 11]]

arr2 = arr.reshape(2,-1) # => -1 : 앞에있는 것 설정하고 남는 것 다 밀어넣어라는 뜻 
print(arr2)
# 결과 : 
#[[ 0  1  2  3  4  5]
# [ 6  7  8  9 10 11]]

arr3 = arr.reshape(-1,4)
print(arr3)
# 결과 : 
#[[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]]

arr4 = np.arange(0,100,1).reshape(5,-1).copy()
print(arr4)
# 결과 : 
#[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
# [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
# [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
# [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
# [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


# 다차원 배열을 1차원으로 만들어보자 (reshape 이용) => ravel()
arr4 = np.arange(0,100,1).reshape(5,-1).copy()
arr5 = np.ravel(arr4)
print(arr5)
# 결과 ; 
#[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
# 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
# 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
# 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
# 96 97 98 99]


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[  0 100   2   3   4   5   6   7   8   9  10  11]
[[  0 100   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]
True
[ True  True  True  True  True  True  True  True  True  True  True  True]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [70]:
# 2. resize 는 reshape과 유사하다. reshape과 다르게 형태가 달라도 error가 발생하지 않는다.
arr =  np.arange(0,10,1)
print(arr)
# 결과 : [0 1 2 3 4 5 6 7 8 9]

# @ resize를 이용하는 1번째 방법 @  => 원본은 안바뀌고 결과값만 받고 싶을 때
# np.resize(np, 튜플) => 변경된 ndarray를 return해준다.
# 사이즈가 늘어났을 때  => 수가 부족한 부분은 배열의 처음부터 다시 시작된다.
np.resize(arr,(2,7))
# 결과 :
#array([[0, 1, 2, 3, 4, 5],
#       [6, 7, 8, 9, 0, 1]])

# 사이즈가 줄어들었을 때 => 앞에서부터 정렬하고 남는 부분은 없앤드
np.resize(arr,(2,2))
# 결과 : 
#array([[0, 1],
#       [2, 3]])



# @ resize를 이용하는 2번째 방법 @ => 원본이 바뀐다.
arr =  np.arange(0,10,1)
result = arr.resize(2,3)
print(result)
# 결과 : None
print(arr)
# 결과 : 
#[[0 1 2]
# [3 4 5]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [118]:
# 3. NumPy array를 가로방향, 세로방향으로  결합하고
# 2행 3열짜리 ndarray 를 생성하자
# 정수로 생성, 랜덤하게 균등분포로 0~10 사이에서 추출하자
# 6개를 추출해서 2차원 ndarray로 생성하자

# 정수 추출 => randint + 항상 균등분포
np.random.seed(1111)
arr1 = np.random.randint(0,10,(2,3))
print(arr1)
# 결과 :  => 현재 seed값이 있기 때문에 같은 수가 도출된다.
#[[7 5 1]
# [2 4 8]]

# 가로 방향으로 결합해보자 => 행의 개수가 맞아야한다!!!
arr2 = np.random.randint(0,10,(2,5))
print(arr2)
# 결과 : 
#[[6 4 8 6 2]
# [6 8 9 3 4]]
result = np.hstack((arr1,arr2))  # 튜플 안에 붙이고 싶은 ndarray를 넣어준다 !
print(result)
# 결과 ; 
#[[7 5 1 6 4 8 6 2]
# [2 4 8 6 8 9 3 4]]


# 세로 방향으로 결합해보자 => 열의 개수가 맞아야한다!!!
arr1 = np.random.randint(0,10,(2,3))
arr2 = np.random.randint(0,10,(3,3))
result = np.vstack((arr1,arr2))
print(result)
# 결과 : 
#[[8 9 9]
# [7 2 0]
# [4 8 5]
# [5 1 2]
# [0 7 5]]


[[7 5 1]
 [2 4 8]]
[[6 4 8 6 2]
 [6 8 9 3 4]]
[[7 5 1 6 4 8 6 2]
 [2 4 8 6 8 9 3 4]]
[[8 9 9]
 [7 2 0]
 [4 8 5]
 [5 1 2]
 [0 7 5]]


In [120]:
# NumPy array의 indexing과 slicing

@@@@@@@@@@@@@@@@@@@@@@@@@@1차원@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
arr = np.arange(10,20,1)
print(arr)
# 결과 : [10 11 12 13 14 15 16 17 18 19]

for i in arr:                        # => 데이터만 추출해서 사용하는 for
    print("data : {}".format(i))
# 결과 : 
#data : 10
#data : 11
#data : 12
#data : 13
#data : 14
#data : 15
#data : 16
#data : 17
#data : 18
#data : 19

for idx,data in enumerate(arr):              # =>  tuple , index와 데이터가 같이 나온다 # enumaerate : index번호, 열거
    print ("index : {} , data : {}".format(idx,data))
# 결과 : 
#index : 0 , data : 10
#index : 1 , data : 11
#index : 2 , data : 12
#index : 3 , data : 13
#index : 4 , data : 14
#index : 5 , data : 15
#index : 6 , data : 16
#index : 7 , data : 17
#index : 8 , data : 18
#index : 9 , data : 19

arr = np.arange(0,5,1)  # list indexing과 똑같다 !!
print(arr[2])
# 결과 :  2

print(arr[1:3])         # slicing도 차이가 없네???????? 싶은데 뭔가 쫌 그런게  있다. 
# 결과 : [1 2]
print(type(arr[1:3]))
# 결과 : <class 'numpy.ndarray'>
print(arr[:3])
# 결과 : [0 1 2]
print(arr[1:])
# 결과 : [1 2 3 4]

# @@@ 
print(arr[1::2])       # 1부터 2개씩 띄어서 출력 하라 
# 결과 : [1 3]
arr2 = np.arange(0,20,1)
print(arr2[3::5])
# 결과 : [ 3  8 13 18]

# 맨 마지막 요소만 슬라이싱 하자
print(arr[4:])          # 얘는 array 사이즈가 늘어나면 못 써ㅠㅠ
# 결과 : [4]
print(arr[-1:])        # 그래서 -1로 표현한다
# 결과 : [4]



#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 2차원 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
# 결과 : 
#[[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]]

# 숫자 6을 가져와보자
print(arr[1,2])

# 첫번째 열만 가져와보자 @@@@@@@중요맨@@@@@@@
print(arr[:,0])
# 결과 : [0 4 8]            => 앞은 slicing, 뒤는 값 => numpy array, int => 1차원 numpy 

print(arr[:,0:1])
# 결과 :                    => 앞은 slicing, 뒤도 slicing => numpy , numpy => 2차원 numpy 
#[[0]
# [4]
# [8]]

# 두번째 행만 가져와보자
print(arr[1:3,1:3])
# 결과 : 
#[[ 5  6]
# [ 9 10]]
# 이를 1차원으로 만들어보자:ravel()이용
print(arr[1:3,1:3].ravel())
# 결과 : [ 5  6  9 10]




[10 11 12 13 14 15 16 17 18 19]
data : 10
data : 11
data : 12
data : 13
data : 14
data : 15
data : 16
data : 17
data : 18
data : 19
index : 0 , data : 10
index : 1 , data : 11
index : 2 , data : 12
index : 3 , data : 13
index : 4 , data : 14
index : 5 , data : 15
index : 6 , data : 16
index : 7 , data : 17
index : 8 , data : 18
index : 9 , data : 19


In [201]:
#@@@@@@@@@@@@@@@@@@@@@@@@Boolean Indexing  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# boolean indexing : mask를 이용해서 배열의 각 요소의 선택 여부를 True, False로 지정해서 True 요소만 선택

# 정수형 난수를 추출해보자
# 0부터 9까지 정수형 난수를 1차원으로 10개 균등분포를 이용하여 추출
np.random.seed(1)
arr = np.random.randint(0,10,(10,))
print(arr)

# 여기에서 짝수만 추출하자
result = list()
for i in arr:
    if i% 2 == 0:
        result.append(i)
result = np.array(result)
print(result)
# 결과 : [8 0 0 6]

# 로직을 이용해서 할 수 있지만 더 쉬운 방법으로 해보자
# 1) 조건에 맞는 mask를 만든다 = list, value=t/f, size =ndarray
# print(df[mask])
print(arr%2==0)
# 결과 : [False  True False False  True  True False False  True False]
print(arr[arr%2==0])
# 결과 : [8 0 0 6]


#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@& Fancy Indexing@@@@@@@@@@@@@@@@@@@@@@@@@
#indexing을 할 때 배열을 이용해서 배열 요소를 찾는 방식
arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
# 결과 : 
#[[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]]
print(arr[2,2])
# 결과 : 10
print(arr[1:2,2])    #=> slicing형태이기 때문에 [] 형태로 나온다.
# 결과 : [6]
arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)

# print(arr[행,열]) 에 숫자나 범위가 나오는 것이 아니라 배열이 나온다!
print(arr[ [0,2]  ,  2   ]) # 0행과 2행의 2열을 도출한다
# 결과 : [ 2 10 ]
print(arr[ 2 , [0,2]  ])
# 결과 : [ 8 10 ] 
print(arr[ [0,2] , 1: ])
# 결과 :
#[[ 1  2  3]
# [ 9 10 11]]
print(arr[:,[0,2]])
# 결과 : 
#[[ 0  2]
# [ 4  6]
# [ 8 10]]

# fancy indexing으로 5 6 9 10 을 추출하고 싶다.
# 시도 1)
print(arr[[1,2],[1,2]]) 
# 결과 : [ 5 10]               => ?????????다른방식으로 표현해줘야 가능하겠다????????? => 행과 열 동시에 fancy indexing 사용 불가

# 시도 2)
print(arr[[1,2]][:,[1,2]])     
# 결과 :                       => arr[  [1,2]  ][:,[1,2]]
#[[ 5  6]                      => "1,2행만 가져와서"[ 행 전부, [1,2]열 ]
# [ 9 10]]

# 시도 3)                      => numpy의 함수 이용
print(arr[np.ix_([1,2],[1,2])])
# 결과 : 
#[[ 5  6]
# [ 9 10]]

[5 8 9 5 0 0 1 7 6 9]
[8 0 0 6]
[False  True False False  True  True False False  True False]
[8 0 0 6]


In [229]:
# ndarray의 연산
# R의 vector연산과 유사하다
np.random.seed(1)
arr1 = np.arange(1,7,1).reshape(2,3).copy()
arr2 = np.random.randint(1,10,(2,3))
print(arr1+arr2)
# 결과 :                         => vector연산
#[[ 7 11  9]
# [ 5  6  8]]
print(arr1 + 10)
# 결과 :                         => 원래는 연산이 안되어야하는데? 이런 경우에는 scalar 값을 broadcasting 시킨다.
#[[11 12 13]                     => 내가 연산하려는 사이즈에 맞춰서 !! => int 10 이 2행 3열의 10으로 채워진 ndarray라고 한다.
# [14 15 16]]

arr2 = np.array([1,2,3])
print(arr1 + arr2)
# 결과 :                         => 1차 배열이 2차 배열로 broadcasting된다. [1 2 3][1 2 3]으로 !!
#[[2 4 6]
# [5 7 9]]

arr3 = np.array([1,2])
print(arr1 + arr3)
# 결과 : ValueError: operands could not be broadcast together with shapes
# 확장 가능한 상태여야지만 broadcasting이 가능하다. 
# 형태가 안 맞으면 broadcasting 불.가.능.

[[ 7 11  9]
 [ 5  6  8]]
[[11 12 13]
 [14 15 16]]
[[2 4 6]
 [5 7 9]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [246]:
############################################# 기본적인 집계(통계)함수#####################################
arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
# 결과 : 
#[[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]]
print(np.sum(arr))                     # numpy가 가진 sum함수를 사용
# 결과 : 66
print(arr.sum())                       # 해당 numpy array가 가진 method를 사용
# 결과 : 66
print(np.cumsum(arr))                  # 누적합, 1차원으로 변환한다.
# 결과 : [ 0  1  3  6 10 15 21 28 36 45 55 66]
print(np.mean(arr))                    # 파이썬에는 mean 없는데 numpy는 있다.
# 결과 : 5.5
print(np.max(arr))        # 11
print(np.min(arr))        # 0
print(np.std(arr))      # 3.452025~
print(np.sqrt(arr))
# 결과 : 
#[[0.         1.         1.41421356 1.73205081]
# [2.         2.23606798 2.44948974 2.64575131]
# [2.82842712 3.         3.16227766 3.31662479]]
print(np.log10(arr))                                   # 자연로그, 상용로그 사용
# 결과 : 
#[[      -inf 0.         0.30103    0.47712125]
# [0.60205999 0.69897    0.77815125 0.84509804]
# [0.90308999 0.95424251 1.         1.04139269]]

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# 축 개념을 이해해보자(axis 개념)
# 만약 axis를 명시하지 않으면, axis를 None으로 설정하고 대상범위를 전체 ndarray로 지정한다.
##### 1차원 ndarray
arr = np.arange(0,5,1)
print(arr)
print(arr.sum())
# 결과 : 10
print(arr.sum(axis=0))
# 결과 : 10
# ^^^^^1차원에서 axis=0이면 열방향을 지칭한다
# ^^^^^axis=1이면 행방향을 지칭한다.
# 하지만 arr은 1차원이므로 행이1개라서 축(axis=0)이 한개만 존재한다.
#print(arr.sum(axis=1))
# 결과 : AxisError: axis 1 is out of bounds for array of dimension 1


##### 2차원 ndarray
arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
print(arr.sum())
# 결과 : 66
print(arr.sum(axis=0)) 
# ^^^^^2차원에서 axis=0이면 행방향을 지칭한다
# ^^^^^axis=1이면 열방향을 지칭한다.
# 결과 : [12 15 18 21]
print(arr.sum(axis=1))
# 결과 : [ 6 22 38]

##### 3차원 ndarray
# ^^^^^axis=0이면  면방향을 지칭한다
# ^^^^^axis=1이면 행방향을 지칭한다.
# ^^^^^axis=2이면 열방향을 지칭한다.

# => 일반 로직으로 프로그램하는 것 보다, 집계함수를 이용해서 처리하는 것이 훨씬 더 효율적 ! 빠름 !

# 응용
np.random.seed(1)

arr = np.random.randint(1,10,(2,5))
(arr>5).sum()
# arr>5 면 True임으로 => sum을 바로 구한다
arr[arr>5].size
# 결과 : 5

# delete() : axis를 기준으로 행과 열을 삭제
# axisf를 지정하지않으면 1차배열로 변환 후, 해당요소를 삭제하며 원본은 유지하고 삭제된 복사본을 return
arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
# 결과 :
#[[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]]

result = np.delete(arr,1) # 1차 배열로 변환한 후 해당 인덱스 삭제
print(result)
# 결과 : [ 0  2  3  4  5  6  7  8  9 10 11]

result2 = np.delete(arr,1,axis = 0)
print(result2)
# 결과 : 
#[[ 0  1  2  3]
# [ 8  9 10 11]]

result3 = np.delete(arr,1,axis = 1)
print(result3)
# 결과 :
#[[ 0  2  3]
# [ 4  6  7]
# [ 8 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
66
[ 0  1  3  6 10 15 21 28 36 45 55 66]
5.5
11
0
3.452052529534663
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
[[      -inf 0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125 0.84509804]
 [0.90308999 0.95424251 1.         1.04139269]]
[0 1 2 3 4]


C:\Users\student\Anaconda3\envs\cpu_env\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in log10
